Doors
fsandel/cub3D pull request #32
Opened 2023-04-24 11:38 UTC by fsandel

- [ ] implemented doors in parser/raycaster and collision detector
- [ ] added door toggle as keyhook, right now bound to space which toggles all surrounding doors in changeable range

2023-04-24 15:13 UTC, philippschwarzmueller requested changes
if you change the approach of checking the proximity of a door to casting a single centered ray instead of checking all fields around we get no segfaults and also dont open doors in the back of the players view

2023-04-24 15:13 UTC, philippschwarzmueller commented on src/doors.c
> +static void	toggle_surrounding_doors(t_window *window)
this segfaults if you are close to the maps border, because it cant iterate over the empty 'outside' cubes

2023-04-24 17:51 UTC, fsandel commented
uwu pls notice me senpai

2023-04-26 07:25 UTC, philippschwarzmueller approved these changes
lgtm

2023-04-26 07:26 UTC, merged